---
- name: install ifupdown
  apt: name=ifupdown state=present

# works on wheezy (or earlier?)
- name: load interfaces.d/ffrl-tunnels for debian wheezy
  lineinfile: dest=/etc/network/interfaces line='source /etc/network/interfaces.d/ffrl-tunnels'
  when: ansible_distribution_release == "wheezy"

# works on jessie
- name: enable interfaces.d for debian jessie
  lineinfile: dest=/etc/network/interfaces line='source-directory /etc/network/interfaces.d'
  when: ansible_distribution_release == "jessie"

- name: ensure /etc/network/interfaces.d exists
  file: dest=/etc/network/interfaces.d state=directory owner=root group=root

- name: add GRE tunnel configuration
  template: src=ffrl-gre-tunnels.j2 dest='/etc/network/interfaces.d/ffrl-tunnels' owner=root group=root mode='0644'

- name: enable tunnels
  command: /sbin/ifup {{ item.name }}
  with_items: ffrl_peers
  register: ifup_result
  changed_when: "'already configured' in ifup_result.stdout"

- name: add kernel table ffrl
  lineinfile: dest=/etc/iproute2/rt_tables regexp='^{{ ffrl_kernel_table }}' line='{{ ffrl_kernel_table }} ffrl'

- name: add wheezy backports for bird
  apt_repository: repo='deb http://http.debian.net/debian wheezy-backports main'
  when: ansible_distribution_release == "wheezy"

- name: install bird via debian-backports
  apt: name=bird state=latest default_release=wheezy-backports update_cache=yes
  when: ansible_distribution_release == "wheezy"

- name: install bird for debian
  apt: name=bird state=present update_cache=yes
  when: ansible_distribution_release == "jessie"

- name: ensure /etc/bird/bird.d exists
  file: dest=/etc/bird/bird.d state=directory owner=root group=root

- name: template /etc/bird/bird.conf
  template: src=bird.conf.j2 dest='/etc/bird/bird.conf' owner=root group=root mode='0644'
  notify:
  - reload bird config

- name: template /etc/bird/bird.d/ffrl.conf
  template: src=ffrl.conf.j2 dest='/etc/bird/bird.d/ffrl.conf' owner=root group=root mode='0644'
  notify:
  - reload bird config

- name: test bird config
  command: bird -c /etc/bird/bird.conf -p
  changed_when: false
  ignore_errors: yes

- name: start bird
  service: name=bird pattern='/usr/sbin/bird -u bird -g bird' state=started

- name: ensure /etc/bird/bird6.d exists
  file: dest=/etc/bird/bird6.d state=directory owner=root group=root

- name: template /etc/bird/bird6.conf
  template: src=bird6.conf.j2 dest='/etc/bird/bird6.conf' owner=root group=root mode='0644'
  notify:
  - reload bird6 config

- name: template /etc/bird/bird.d/ffrl6.conf
  template: src=ffrl6.conf.j2 dest='/etc/bird/bird6.d/ffrl6.conf' owner=root group=root mode='0644'
  notify:
  - reload bird6 config

- name: test bird6 config
  command: bird6 -c /etc/bird/bird6.conf -p
  changed_when: false
  ignore_errors: yes

- name: start bird6
  service: name=bird6 pattern='/usr/sbin/bird6 -u bird -g bird' state=started
